from random_games.tableau_manager import TableauManager
from random_games.game_logic import JeuDeTacquin
from random_games.random_list_generator import RandomListGenerator
from random_games.html_report_generator import HTMLReportGenerator

def main():

    #Set parameters
    word_length = 100
    initial_value = 0.5

    #Generate random word
    random_word = RandomListGenerator(word_length, initial_value).generate_list()

    # Create a Young tableau
    tableau_manager = TableauManager(random_word)
    young_tableau = tableau_manager.insertion_tableau

    # Find path
    jeu = JeuDeTacquin(random_word)
    path = jeu.find_path(young_tableau)

    # Draw Young tableau with path
    image_file_name = 'example_report_path.jpg'
    tableau_manager.draw_young_table(image_file_name, 'example_path_report', path)

    #Prepare report content
    title = 'Example Report'
    content = ['This is an example report generated by the HTMLReportGenerator class.',
               'It contains a Young tableau with a path.']

    # Generate HTML report

    report_generator = HTMLReportGenerator(title, content, image_file_name)
    report = report_generator.generate_report(title, content)

    report_file_name = 'example_report.html'
    with open(report_file_name, 'w') as file:
        file.write(report)

    print(f'Report is saved to {report_file_name}')

if __name__ == "main":
    main()